### PR TITLE
Modified the about section

### PR DESCRIPTION
**Pull request by devrudra9**
Screenshot 2023-10-29 010811
Completed assigned issue #30

### CODE REVIEW

**Comment by devrudra9** [comment]
Please merge my PR #40 and add `hacktoberfest accepted` label to it.

**Comment by Kavyam172** [comment]
@devrudra9 Attach some screenshots regarding the changes you have made and also link the issue you have solved to this PR.

**Comment by Kavyam172** [comment]
@devrudra9 Great Work.

**Comment by devrudra9** [comment]
Hii @Kavyam172 add the hactoberfest accepted label too to this PR

**Pull request merged**
