### PR TITLE
Changes were made to Contact Us page

### PR DESCRIPTION
**Pull request by Sneha-S-D**
The form was aligned and the color and opacity of the background was adjusted.

### CODE REVIEW

**Comment by Kavyam172** [comment]
@Sneha-S-D Attach screenshots of the changes you have made.

**Comment by Sneha-S-D** [comment]
Screenshot (101)

**Comment by Sneha-S-D** [comment]
> Screenshot (101)

@Kavyam172   These are the changes made

**Comment by Kavyam172** [comment]
@Sneha-S-D Align the form element to the right.

**Comment by Sneha-S-D** [comment]
> @Sneha-S-D Align the form element to the right.

Screenshot (106)
@Kavyam172 Aligned the form element towards right

**Pull request merged**
