### PR TITLE
Added FAQ Section to the Cafe Management Project

### PR DESCRIPTION
**Pull request by saurav1207**
Hello, 

I added Frequently Asked Questions (FAQ) section to the Cafe Management project.
Please review the code and consider merging this pull request. 

Thank you!!

faq section

### CODE REVIEW

**Comment by Kavyam172** [comment]
@saurav1207 Try adding some background to the page .

**Comment by Kavyam172** [comment]
Also add a customer review section just below this.

**Comment by Kavyam172** [comment]
> @saurav1207 Try adding some background to the page.

@saurav1207 Try this as well.

**Comment by saurav1207** [comment]
Hi @Kavyam172,

I have made an update to the FAQ page. I have added a background image to enhance the visual appeal of the page. You can review the changes and, if needed, change the background image to better suit your requirements.


faqwithbg


faqwithbg1

**Review by Kavyam172 — CHANGES_REQUESTED** [review]
@saurav1207 Try a background that matches the website design theme.

**Comment by saurav1207** [comment]
I've made the requested changes and added a hover effect to enhance the aesthetics and create a more engaging user experience. You can review the code and, if you're satisfied, please consider merging it.

Review Image 1

Review Image 2

**Pull request merged**
