### PR TITLE
Order page was made user friendly.

### PR DESCRIPTION
**Pull request by Light13008**
The checkout page/Oder file was made user friendly, and all Indian states were added.
Background color of h2 was changed from black, to give it a visually appealing look.

### CODE REVIEW

**Review by Kavyam172 — CHANGES_REQUESTED** [review]
@Light13008 Good work. A few more things you can do in design:
1. Darken the background a little using darken effect.
2. Decrease the width of all elements(inputs , headers, div, etc.)

**Comment by Light13008** [comment]
sure, will be done soon.

**Comment by Kavyam172** [comment]
@Light13008 Keep the form alignment as the previous one and reduce the width of input elements a little

**Review by Kavyam172 — CHANGES_REQUESTED** [review]
@Light13008 Keep the form alignment as the previous one and reduce the width of input elements a little

**Comment by Light13008** [comment]
yes working on it.

**Comment by Kavyam172** [comment]
@Light13008 nice work

**Pull request merged**
