### PR TITLE
Modified the NavBar and landing page 

### PR DESCRIPTION
**Pull request by kshitizvardhan**
# Issue: Enhancing the NavBar and landing page #4 

## Description

This issue was raised to enhance the NavBar and landing page of the project. The issue has now been resolved, and this provides an overview of the changes made.

## Changes Made

The following changes were made to resolve the issue:

1. **NavBar Enhancements:**
   - Added hovering with transition effects on various links
   - Updated styling and alignment of the links to the right 

2. **Landing Page Enhancements:**
   - Styled Button while hovering and added transition effects.
   - Added a Box shadow on button during hover.

Issue resolved: #4 

Screenshot 2023-10-21 224608

https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/143323194/34690d94-67c7-40c7-94e3-815b4bf2b358

### CODE REVIEW

**Review by Kavyam172 — CHANGES_REQUESTED** [review]
@kshitizvardhan  The navbar is not responsive. It was responsive earlier , so you can refer to the original code for that. Also i would like you to write the CSS for navbar in 'mynav.css' file.
The texts for the navbar links should be in a single line and the 'FAQ' link is going out of the navbar. I would like you to make these corrections.
I am attaching the preview of your code below.
image

**Comment by kshitizvardhan** [comment]
@Kavyam172 I will work on these changes  and provide update to this pull request.

**Comment by kshitizvardhan** [comment]
## Changes Requested Are Done #5 

@Kavyam172 
I have made the requested changes to the responsive navbar and added the necessary CSS to the 'mynav.css' file. The navbar links are now in a single line, and the 'FAQ' link no longer extends beyond the navbar. 

Screenshot 2023-10-22 134211


https://github.com/Open-Source-Chandigarh/Cafe-Management/assets/143323194/d266145c-b364-4471-8afe-04e3f33021d5

**Review by kshitizvardhan — COMMENTED** [review]
Changes Done

**Pull request merged**
