### PR TITLE
Added "Forgot Password?" link to login page[FIX#23]

### PR DESCRIPTION
**Pull request by Srishdwi02**
I have added the forgot password link to login page.
issue number(#23)

### CODE REVIEW

**Comment by Srishdwi02** [comment]
Sure

**Comment by Srishdwi02** [comment]
@Kavyam172 I have made the required changes in the login.html file. Kindly merge this.
I will be creating a new issue for the forgot password page and thereafter I will create a PR for the same.

**Comment by Srishdwi02** [comment]
I have to upload a html file and I can't do that in the same PR.

**Comment by Srishdwi02** [comment]
@Kavyam172 I have created the forgot password page.

**Comment by Kavyam172** [comment]
@Srishdwi02 Great work.

**Pull request merged**
