### PR TITLE
signup and login pages

### LINKED ISSUE #8: Add login and signup pages

### PR DESCRIPTION
**Pull request by SanjanaReddy7707**
Fixes #8 

Screenshot 2023-10-23 205319

Screenshot 2023-10-23 205305

### CODE REVIEW

**Comment by Kavyam172** [comment]
@SanjanaReddy7707 Good work. Just a few changes:
1. Try reducing the width of the box a little.
2. Add an option that directs user from login page to signup page and visa versa.
3. Also add an option to go back to home page.

**Review by Kavyam172 — CHANGES_REQUESTED** [review]
@SanjanaReddy7707 Good work. Just a few changes:

1. Try reducing the width of the box a little.
2. Add an option that directs user from login page to signup page and visa versa.
3. Also add an option to go back to home page.

**Comment by SanjanaReddy7707** [comment]
Screenshot 2023-10-24 184438

Screenshot 2023-10-24 184450

**Comment by SanjanaReddy7707** [comment]
> @SanjanaReddy7707 Good work. Just a few changes:
> 
> 1. Try reducing the width of the box a little.
> 2. Add an option that directs user from login page to signup page and visa versa.
> 3. Also add an option to go back to home page.

Done with the changes @Kavyam172 
I have submitted the PR

**Comment by Kavyam172** [comment]
@SanjanaReddy7707 Good work done.

**Pull request merged**
